openapi: 3.0.3

info:
  title: Kitchen API
  description: API that allows you to manage kitchen service for CoffeeMesh
  version: 1.0.0


servers:
  # Добавление URL серверов для тестирования endpoints
  - url: http://localhost:7655  # Тестирование на локальном сервере
    description: URL for local development and testing
  - url: https://coffeemesh.com
    description: main production server
  - url: https://coffeemesh-staging.com
    description: staging server for testing purposes only


# /kitchen/schedules
# (POST) - позволяет запланировать заказ на изготовление 
# (GET) - получить список запланированных заказов

# /kitchen/schedules/{schedule_id} -
# (GET) получить информацию о запланированном заказе
# (PUT) обновить информацию о нем
# (DELETE) удалить заказ

# /kitchen/schedules/{schedule_id}/status -
# (GET) получить статус запланированного заказа

# /kitchen/schedules/{schedule_id}/cancel -
# (POST) отменить запланированный заказ 

paths:
  /kitchen/schedules: # endpoint
    get:  # тип запроса 
      parameters:  # параметры запроса
        - name: progress
          in: query
          required: false  # обязательный ли запрос
          schema:
            type: boolean
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: since
          in: query
          required: false
          schema:
            type: string
            format: date-time
      summary: list of shedules
      operationId: getShedules
      description: >
        A list of schedelu made by customer sorted 
        by progress status and/or limit count
      responses:  # Модели ответов
        "200":
          description: A JSON array of shedule order
          content:
            application/JSON:
              schema:
                type: object
                properties:
                  order:
                    $ref: '#/components/schemas/GetScheduleOrdersSchema'
        "422":
          $ref: '#/components/responses/UnprocessableEntity'
      
    post:
      summary: create shedule
      operationId: createShedules
      description: >
        A JSON representation of the created shedule
      requestBody:
        required: true
        content:
          application/JSON:
            schema:
              $ref: '#/components/schemas/ScheduleOrderSchema'
      responses:
        "201":
          description: A schedule of create
          content:
            application/JSON:
              schema:
                $ref: '#/components/schemas/GetScheduleOrderSchema'
        "422":
          $ref: '#/components/responses/UnprocessableEntity'

      
  /kitchen/{schedule_id}:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: UUID

    get:  # тип запроса 
      summary: get schedule by id
      operationId: getSchedule
      responses:  # Модели ответов
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScheduleOrderSchema'
        "404":
          $ref: '#/components/responses/NotFound'
        "422":
          $ref: '#/components/responses/UnprocessableEntity'
    
    put:
      summary: put order by id
      operationId: putOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleOrderSchema'
      responses:  # Модели ответов
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScheduleOrderSchema'
        "404":
          $ref: '#/components/responses/NotFound'
        "422":
          $ref: '#/components/responses/UnprocessableEntity'

    delete:
      summary: put order by id
      operationId: deleteOrder
      responses:  # Модели ответов
        "204":
          description: the resource was deleted is successfully
        "404":
          $ref: '#/components/responses/NotFound'
        "422":
          $ref: '#/components/responses/UnprocessableEntity'

  /kitchen/{schedule_id}/cancelled:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: UUID
    post:
      operationId: postOrdersCancelled
      description: >
        Cancelled order by id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScheduleOrderSchema'
        "404":
          $ref: '#/components/responses/NotFound'
        "422":
          $ref: '#/components/responses/UnprocessableEntity'
  
  /kitchen/{schedule_id}/status:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: UUID
          
    get:  # тип запроса 
      summary: get schedule by id
      operationId: getStatusSchedule
      responses:  # Модели ответов
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScheduleOrderSchema'
        "404":
          $ref: '#/components/responses/NotFound'
        "422":
          $ref: '#/components/responses/UnprocessableEntity'
        

components:
  responses:
    NotFound:
      description: not found resource response
      content:
        application/JSON:
          schema:
            $ref: '#/components/schemas/Error'
    UnprocessableEntity:
      description: payload value is invalid
      content:
        application/JSON:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        details:
          oneOf:
            - type: string
            - type: array
      required:
        - details
    OrderItemSchema:
      additionalProperties: false  # Запрещает использование доп. полей в модели
      type: object
      required:
        - product
        - size
      properties:
        product:
          type: string
        size:
          type: string
          enum:
            - small
            - medium
            - big
        quantity:
          type: integer
          format: int64
          default: 1
          minimum: 1
          maximum: 1000000
    ScheduleOrderSchema:
      additionalProperties: false  # Запрещает использование доп. полей в модели
      type: object
      required:
        - order
      properties:
        order:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderItemSchema'
    GetScheduleOrderSchema:
      additionalProperties: false  # Запрещает использование доп. полей в модели
      type: object
      required:
        - id
        - create
        - status
        - order
      properties:
        id:
          type: string
          format: UUID
        created:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - pending
            - progress
            - cancelled
            - finished 
        order:
          $ref: '#/components/schemas/OrderItemSchema'
    GetScheduleOrdersSchema:
      additionalProperties: false  # Запрещает использование доп. полей в модели
      type: object
      required:
        - shedules
      properties:
        shedules:
          $ref: '#/components/schemas/GetScheduleOrderSchema'
    SheduleStatusSchema:
      additionalProperties: false  # Запрещает использование доп. полей в модели
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - pending
            - progress
            - cancelled
            - finished

